In [4]:
import numpy as np

In [5]:
id=np.arange(1,101)

In [6]:
idade=np.random.randint(18,101,100)

In [7]:
lista_sexo = np.array(['F', 'M'])
sexo = np.random.choice(lista_sexo, 100)

In [8]:
lista_estado_civil = np.array(['solteiro', 'casado', 'divorciado', 'viuvo'])
estado_civil = np.random.choice(lista_estado_civil, 100)

In [9]:
sinistro=np.random.randint(0,2,100)

In [20]:
premio=np.random.randint(0,1000001,100)/100

In [33]:
#np.savetxt('premio_teste.txt', premio)
#np.loadtxt('premio_teste.txt')

In [11]:
#exercicio 2
contador=0
for i in idade:
    if i>30:
        contador+=1
contador

87

In [22]:
#exercicio 3
base=np.column_stack([id, premio, sinistro])
lista=[]
for i in base:
    if i[1]>1000 and i[2]==0:
        lista.append(i)
lista

[array([2.00000e+00, 8.18673e+03, 0.00000e+00]),
 array([4.00000e+00, 7.25753e+03, 0.00000e+00]),
 array([   8.  , 1485.52,    0.  ]),
 array([   9.  , 5928.11,    0.  ]),
 array([  10.  , 8479.11,    0.  ]),
 array([  13.  , 1410.24,    0.  ]),
 array([  14.  , 5538.62,    0.  ]),
 array([  17.  , 3836.02,    0.  ]),
 array([  19.  , 9033.87,    0.  ]),
 array([  23.  , 3802.76,    0.  ]),
 array([  24.  , 7852.68,    0.  ]),
 array([  26.  , 5976.66,    0.  ]),
 array([  29.  , 8765.28,    0.  ]),
 array([  30.  , 9737.64,    0.  ]),
 array([  33. , 6217.1,    0. ]),
 array([  34.  , 6814.61,    0.  ]),
 array([  39.  , 2927.76,    0.  ]),
 array([  40.  , 2300.22,    0.  ]),
 array([  42.  , 8017.65,    0.  ]),
 array([  43.  , 7911.59,    0.  ]),
 array([  44.  , 4530.26,    0.  ]),
 array([  45.  , 1720.38,    0.  ]),
 array([  46.  , 5062.06,    0.  ]),
 array([  47.  , 6285.49,    0.  ]),
 array([  49.  , 4897.95,    0.  ]),
 array([  50. , 8541.5,    0. ]),
 array([  53.  , 358